config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  
  devise_for :users
  resources :water_tanks
  resources :users

  root 'water_tanks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :water_tanks
end

app/models/water_tank.rb
class WaterTank < ApplicationRecord

  geocoded_by :address
  after_validation :geocode

  has_attached_file :image, styles: { medium: "400x300>", thumb: "200x150>", default_url: "/images/:style/chicago_water_tanks_logo.png" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_water_tanks = @user.water_tanks
  end
end

app/controllers/water_tanks_controller.rb
class WaterTanksController < ApplicationController
  before_action :set_water_tank, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /water_tanks
  # GET /water_tanks.json
  def index
    @water_tanks = WaterTank.all
    @hash = Gmaps4rails.build_markers(@water_tanks) do |tank, marker|
      marker.lat tank.latitude
      marker.lng tank.longitude
      marker.infowindow tank.nickname
    end
  end

  # GET /water_tanks/1
  # GET /water_tanks/1.json
  def show
  end

  # GET /water_tanks/new
  def new
    @water_tank = current_user.water_tanks.build
  end

  # GET /water_tanks/1/edit
  def edit
  end

  # POST /water_tanks
  # POST /water_tanks.json
  def create
    @water_tank = current_user.water_tanks.build(water_tank_params)

    respond_to do |format|
      if @water_tank.save
        format.html { redirect_to @water_tank, notice: 'Water tank was successfully created.' }
        format.json { render :show, status: :created, location: @water_tank }
      else
        format.html { render :new }
        format.json { render json: @water_tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /water_tanks/1
  # PATCH/PUT /water_tanks/1.json
  def update
    respond_to do |format|
      if @water_tank.update(water_tank_params)
        format.html { redirect_to @water_tank, notice: 'Water tank was successfully updated.' }
        format.json { render :show, status: :ok, location: @water_tank }
      else
        format.html { render :edit }
        format.json { render json: @water_tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /water_tanks/1
  # DELETE /water_tanks/1.json
  def destroy
    @water_tank.destroy
    respond_to do |format|
      format.html { redirect_to water_tanks_url, notice: 'Water tank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_water_tank
      @water_tank = WaterTank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def water_tank_params
      params.require(:water_tank).permit(:latitude, :longitude, :nickname, :address, :neighborhood, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/water_tanks_helper.rb
module WaterTanksHelper
end

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer font-small stylish-color-dark pt-4 mt-4">

    <hr>

    <!--Call to action-->
    <div class="text-center py-3">
        <ul class="list-unstyled list-inline mb-0">
            <li class="list-inline-item">
                <h5 class="mb-1">Help us map Chicago's historic water tanks</h5>
            </li>
            <li class="list-inline-item">
                <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-primary btn-rounded"  %>
            </li>
        </ul>
    </div>
    <!--/.Call to action-->

    <hr>



    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        © 2018 Copyright
        <%= link_to "Chicago Water Tanks", root_path %>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron text-center">
  <h1 class="display-3">Chicago Water Tanks</h1>
  <p class="lead">Help map historical water tanks around the city of Chicago.<br><br> Sign up today and start mapping!</p>
  <div class="button-wrapper">
    <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-primary btn-rounded"  %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Chicago Water Tanks</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Chicago Water Tanks", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path  %></li>
            <li><%= link_to "Sign In", new_user_session_path  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>

    <%= render "layouts/footer" %>

  </div>
</body>
</html>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= @user.email %></h1>
</div>

<% @user_water_tanks.each do |tank| %>
  <ul>
  <li><%= link_to "#{tank.nickname}", water_tank_path(tank) %></li>
  </ul>

<% end %>

app/views/water_tanks/_form.html.erb
<%= form_for(@water_tank, html: { class: "form-horizontal", role: "form", multipart: true }) do |f| %>
  <% if @water_tank.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@water_tank.errors.count, "error") %> prohibited this water_tank from being saved:</h4>

      <ul>
      <% @water_tank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :latitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nickname, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nickname, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :neighborhood, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :neighborhood, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/water_tanks/edit.html.erb
<div class="page-header">
  <%= link_to water_tanks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @water_tank, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing water_tank</h1>
</div>

<%= render 'form' %>

app/views/water_tanks/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyB4bjalZ_yxT3gIMZdRJQQJGd124LPJKoI"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<div class="page-header">

  <% if !user_signed_in? %>
    <%= render "layouts/jumbotron" %>
  <% end %>

  <% if user_signed_in? %>
    <div class="button-wrapper">
      <%= link_to "Map a Water Tank", new_water_tank_path, class: "btn btn-primary btn-rounded btn-lg"  %>
    </div>
  <% end %>

</div>

<div style='width: 1200px;'>
  <div id="map" style='width: 1200px; height: 400px;'></div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nickname</th>
            <th>Address</th>
            <th>Neighborhood</th>
            <th>User</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Image</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @water_tanks) do |water_tank| %>
            <td><%= water_tank.nickname %></td>
            <td><%= water_tank.address %></td>
            <td><%= water_tank.neighborhood %></td>
            <td><%= water_tank.user.email %></td>
            <td><%= water_tank.latitude %></td>
            <td><%= water_tank.longitude %></td>
            <td><%= image_tag water_tank.image.url(:thumb) %></td>
            <td><%= link_to 'Show', water_tank %></td>
            <% if water_tank.user == current_user %>
              <td><%= link_to 'Edit', edit_water_tank_path(water_tank) %></td>
              <td><%= link_to 'Delete', water_tank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
</script>

app/views/water_tanks/new.html.erb
<div class="page-header">
  <%= link_to water_tanks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New water_tank</h1>
</div>

<%= render 'form' %>

app/views/water_tanks/show.html.erb
<div class="page-header">
  <%= link_to water_tanks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_water_tank_path(@water_tank), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @water_tank.nickname %></h1>
  <h3><%= @water_tank.neighborhood %></h3>
</div>

<dl class="dl-horizontal">
  <dt>Latitude:</dt>
  <dd><%= @water_tank.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @water_tank.longitude %></dd>

  <dt>Nickname:</dt>
  <dd><%= @water_tank.nickname %></dd>

  <dt>Address:</dt>
  <dd><%= @water_tank.address %></dd>

  <dt>Neighborhood:</dt>
  <dd><%= @water_tank.neighborhood %></dd>

  <dt>Image:</dt>
  <dd><%= image_tag @water_tank.image.url(:medium) %></dd>

</dl>